### ISSUE TITLE
Default user agent string is used when customizing it to an empty string

### ISSUE THREAD

**Issue by Javran** [anthonycr/Lightning-Browser#125]
Use an empty string as user agent and browse websites that can check your UA (e.g. [this one](http://www.useragentstring.com/)), Lightning browser will still use the default setting, however the customization works if I leave a single space as UA.

**Comment by anthonycr** [comment]
I know this is old, and sorry that I didn't fix it sooner. You might not be using lightning any more, but I added in a check for empty or null and set it to a single space and it sets an empty user agent. Fixed in commit: https://github.com/anthonycr/Lightning-Browser/commit/04c9f75a9039ec86d31374cb574572c73bf389e1

**Comment by Javran** [comment]
ah nice work, thanks!
