### ISSUE TITLE
Disable SSLv3 and weak cipher suits

### ISSUE THREAD

**Issue by pejakm** [anthonycr/Lightning-Browser#156]
Title says all.
More info here about weak cipher suits: https://www.ssllabs.com/ssltest/viewMyClient.html

Basically, weak ciphers are:

```
SRP-AES-256-CBC-SHA
SRP-AES-128-CBC-SHA
ECDHE-RSA-RC4-SHA
ECDHE-ECDSA-RC4-SHA
ECDH-RSA-RC4-SHA
ECDH-ECDSA-RC4-SHA
RC4-SHA
RC4-MD5
```

**Comment by pejakm** [comment]
I think this would do for the the protocols part, if put in the right place:

```
		if (API > 16) {
			???.setEnabledProtocols("TLSv1.1", "TLSv1.2");
		} else {
			???.setEnabledProtocols("TLSv1");
		}
```

:)

**Comment by revuwa** [comment]
The part with "disable SSLv3" was exactly what I wanted to say within the issue: https://github.com/anthonycr/Lightning-Browser/issues/136, too.

The part with "weak ciphers" seems to be (partially) managed inside the android source code (AOSP). At least on the <5.X versions, unless I'm very much mistaken...
Please have a look at this very interesting (deep diving) overview here: 
http://op-co.de/blog/posts/android_ssl_downgrade/
Note to this article: IMHO the cipher order is not that relevant, because I think the server is choosing the strongest cipher (over handshake) - not the client.

And IMHO² you should not remove (all) the weak ciphers because of the backward compatibility to some (older!) sites; probably it's better to encrypt with weak ciphers on that kind of sources instead of using them unencrypted, or what do you think about that?

**Comment by pejakm** [comment]
> probably it's better to encrypt with weak ciphers on that kind of sources instead of using them unencrypted

It's better to have no encryption at all than to have possibly compromised encryption. Using the latter provides false sense of security.

**Comment by revuwa** [comment]
I've tried to make a (ugly) comparison of Lightning v4.0.3a-beta and the mobile version of the Firefox v36.0.4 to illustrate what we mean:
![comp](https://cloud.githubusercontent.com/assets/7300276/6930996/cbd145a6-d808-11e4-81f1-e1a3e93746ca.png)

sources:
Lightning logo: https://github.com/anthonycr/Lightning-Browser
Firefox logo: https://www.mozilla.org/en-US/firefox/new/
FREAK vulnerability check: https://freakattack.com/
all other test results: https://www.ssllabs.com/ssltest/viewMyClient.html

**Comment by anthonycr** [comment]
This is obviously an issue, but I don't see any way to fix it other than to stop using the WebView. Lollipop WebView isn't vulnerable to this attack, but older versions are.

**Comment by tpeg5stan** [comment]
May 2016, more than one year after, lightning is STILL vulnerable to logjam, freak, poodle, and does not support TLS 1.2 :/
https://www.ssllabs.com/ssltest/viewMyClient.html
Do you know is there is/there will be a way to get rid of it ?

**Comment by kuc** [comment]
>Do you know is there is/there will be a way to get rid of it ?

Upgrade your Android version.

**Comment by brevilo** [comment]
> but I don't see any way to fix it

You already use NetCipher for Orbot support. Why not use it for SSL/TLS as well? It's its main purpose after all. Looking into it...

**Comment by Yowlen** [comment]
@kuc is right. If you're still vulnerable, it's your WebView that's outdated. If you have Lollipop and above, you can upgrade the WebView using the Play Store or GApps. If you're completely sans Google, then you'll have to get your ROM manufacturer to update the AOSP WebView. For Kit Kat and below, your only choices are upgrading to Lollipop or above, or Orbot. The latter isn't recommended because other security vulnerabilities exist in Kit Kat such as DNS requests being handled outside the proxy.

But, yeah, with the latest WebView, all issues are solved.
![screenshot_2017-03-25-09-08-05](https://cloud.githubusercontent.com/assets/17078692/24322481/773858a4-113b-11e7-99a3-191c3234e75c.png)

**Comment by pejakm** [comment]
@Yowlen, I reported the issue in 2014.
