### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by DF1E** [anthonycr/Lightning-Browser#200]
Android Studio is the official development platform of Android apps for some time. Now I want to ask you if you will leave Eclipse because its much easier..

**Comment by kuc** [comment]
?

I imported this project into Android Studio long time ago, and it worked just fine for me. You could even use Notepad++ and build app from command line, if you want.

**Comment by anthonycr** [comment]
Switching to android studio is the first thing I'm going to do once I publish a stable lollipop update. I haven't done it yet because I didn't want to muck up the lollipop commits with a structural change. This is the last project of mine that's still on eclipse and it's painful haha.

I've tested importing to Android studio and it works fine so it should be an easy change.

**Comment by anthonycr** [comment]
Today is the day, I'm switching to gradle and Android studio finally. I'll be adding changes to dev and then merging into master when it's working.

**Comment by vibhor4all** [comment]
When I imported your Lightning Browser project in Android Studio I got the following error while building gradle...
Error:Configuration with name 'default' not found.

I googled the error and I found that the problem is related with library file of "libnetcipher" which is missing from the "external/netcipher/libnetcipher" folder.
Please provide the necessary files ASAP.

**Comment by karolba** [comment]
@vibhor4all Please read the README.md file ASAP. Especially the section called "Setting Up the Project".

**Comment by chrisharris007** [comment]
i have given this git submodule update --init --recursive.but again  Error:Configuration with name 'default' not found. please help
