### ISSUE TITLE
When fullscreen mode is enabled, the address bar hides the top part of the website

### ISSUE THREAD

**Issue by moray33** [anthonycr/Lightning-Browser#223]
When fullscreen mode is enabled, the address bar hides the top part of the website. It's really annoying when the website has a menu bar at the top. When fullscreen mode is not enabled, the address bar doesn't happens. You can see it, for example, in Facebook's mobile website.

**Comment by anthonycr** [comment]
Swipe down on the page when at the top and the address bar will hide itself.

**Comment by moray33** [comment]
Yes, but it's not very handy. Other browsers don't behave like this. I think it would be better to change it.

**Comment by cathos** [comment]
This behavior also hides half of the copy/paste menu when selecting text at the top of a page.

**Comment by shorty66** [comment]
It does not hide anything of the copy/paste menu on my phone. Do you use the latest version?
I like the behaviour as it is in the latest version.

**Comment by cathos** [comment]
I am using the latest version of the browser. The copy/paste menu is served
by the newest version of HTC Sense 7 on Android 5.02.

**Comment by kppmsd** [comment]
First of all, thanks for all of your great work with the browser :)

I'm also having some issues with address bar on full screen mode.

when you try to access the top of a web page, you swipe up which makes the address bar appear hiding the top of the web page. Swiping down hides the address bar, but then again by scrolling down also hides the top of the web page, which makes the top of the page pretty much inaccessible. Youtube is a good example of a page where this can get really annoying.

Maybe the address bar could be always visible when you reach the top of the web page, and then the web content could be scrolled down so that the top of the page starts at the bottom of the address bar (hard to explain but I hope you can understand what I'm suggesting).

**Comment by shorty66** [comment]
If the adressbar is shown and you reached the top of the page, 'swiping up' again hides the addressbar.

**Comment by anthonycr** [comment]
Fixed in latest dev
