### ISSUE TITLE
Bookmark item click is not working

### ISSUE THREAD

**Issue by DF1E** [anthonycr/Lightning-Browser#292]
Since the latest bookmark changes we can't open pages with a click on a bookmark item.

**Comment by anthonycr** [comment]
What device/sdk version are you seeing this on? On Lollipop I am able to click bookmark items, I have not tested on other versions yet though and I am running a debug build.

If you are seeing it on a release build, I wonder if it could be proguard stripping out the methods subscribed to the event bus.

**Comment by DF1E** [comment]
I use Android 5.1.1 and I build this app on latest sources yesterday..

**Comment by anthonycr** [comment]
Ok, I am fairly certain it's a proguard problem as the appropriate guards have not been added to the proguard file to keep the @ Subscribe annotated methods from getting stripped out. I can't make any more changes or test until tomorrow, but if you want to fix your local build before then, take a look at [this documentation](http://square.github.io/otto/) where it shows what lines to add to the proguard file. Otherwise, I'll have a fix added tomorrow.

**Comment by DF1E** [comment]
You're right, with the following lines on proguard it works:
```
-keepattributes *Annotation*
-keepclassmembers class ** {
    @com.squareup.otto.Subscribe public *;
    @com.squareup.otto.Produce public *;
}
```

**Comment by anthonycr** [comment]
Fixed in https://github.com/anthonycr/Lightning-Browser/commit/919043cad9acb9594dd1bb9c9d5691f3dd80e1e5
