### ISSUE TITLE
FC when opening settings

### ISSUE THREAD

**Issue by lombartz** [anthonycr/Lightning-Browser#329]
since commit 94b69fd328d8a00abb6834658798558233d91009
tested on 4 different devices, no way to open settings dialog, app crashes immediately

**Comment by anthonycr** [comment]
Acknowledged. Looking for a fix now. I was able to reproduce on ICS.

**Comment by anthonycr** [comment]
Problem is due to the AppCompatDelegate used in the AppCompatePreferenceActivity, my current solution is to stop using it :-/ and just roll with the platform implementation of the preference activity and inject my own toolbar. It could be that there is a bug in the AppCompatPreferenceActivity code. I need to investigate further, more likely scenario is that the support library is broken for this use case.

**Comment by anthonycr** [comment]
Pretty sure I fixed it in https://github.com/anthonycr/Lightning-Browser/commit/cb98ee783b6607635579f606a9c19f0ae388796c It's a bug in the support library from what I gather.

Can you confirm?

**Comment by lombartz** [comment]
Hi,

yes, seems to be fixed. Tested on 2 devices with 4.2 & 4.4 for now.

best regards,

Martin
--

M.Wersig


Am 6. November 2015 03:24:36 MEZ, schrieb Anthony Restaino <notifications@github.com>:
