### ISSUE TITLE
Latest releases do not have apk in release section, 4.5.1, 4.5.0

### ISSUE THREAD

**Issue by rancidfrog** [anthonycr/Lightning-Browser#608]
Is there a reason why apk no longer attached in release section?

Has it got something to do with your "sex count plugin" ~ https://github.com/anthonycr/Lightning-Browser/commit/3318d09a23d2c372b7e5c472b1431e1b99a13cd8 ?

**Comment by anthonycr** [comment]
Yes it's no longer attached because the APK is available on F-Droid, which is a more reliable source for the release since they independently build and verify the APK from this repo. I suggest you download the APK from there, as it will always have the latest and will notify you when a new version is available.

As for "sex count plugin" that commit is the unfortunate victim of MacOS autocorrect... It doesn't know the word Dex (android's binary format) and changed the word in my commit.

**Comment by rancidfrog** [comment]
Fdroid sometimes lags on updates. Also, it makes more sense to download from source than 3rd party.
I just do not see why remove apk when you already had it in release section.
Many project also have automatic mechanism to add apk to releases.

I thought, as some other devs do sometimes unfortunately, that you were trying to keep count of downloads or something.

Thank you for response

**Comment by anthonycr** [comment]
F-droid updates should no longer lag behind the play store or the tags here because as of the latest update, I turned on auto update for Lightning in F-droid. So now instead of requiring manually updating the version in F-droid, their system is notified when I release an update and queue it up to be built and published. While F-droid is technically a 3rd party, it's an open source project that I respect and is how I am choosing to distribute the APK from now on.
