### ISSUE TITLE
Is Lightning Browser still alive?

### ISSUE THREAD

**Issue by Buntbart** [anthonycr/Lightning-Browser#724]
The developer hasn't written anything here for a long time and the last update was done a long time ago. I'd be happy to get a statement from anthonycr if there's more development to come or if I'd better look for another browser.
That would be a pity, because Lightning has been my favourite browser for a long time. But if nothing happens here anymore, I'll have to change.

**Comment by puppykickr** [comment]
What is wrong that you need changed?

Aside from a couple of bugs, I find it to be the best browser around.

There are even multiple (at least two) copycats of it on Google PlayStore.

**Comment by Buntbart** [comment]
I have reported two bugs that bother me here and received no significant reaction. I also suspect that the ad filter might need some maintenance to work properly again. Instead of Google Playstore I use F-Droid. I avoid copycats as much as possible, especially if it contains a link to the Jehovah's Witnesses and crashes as soon as you deny access to the location services... 
I can understand that software development takes a lot of time and that the cheeky attitude of some users is hard to bear. I am grateful for the software as it is, and I would be happy to wait and donate some money if it helps. But if anthonycr doesn't react at all, then I'd have to say goodbye.

**Comment by sgelb** [comment]
There are at least two very active branches.

**Comment by puppykickr** [comment]
@buntbart
I have used both Stealth Browser and LiteSpeed Browser, and never found any link to the Jehovah's Witnesses, and I always have my location off and never had any problems.

It was through those apps that I found Lightning.

No ad filter has ever worked perfect for me, but I notice a big difference if I turn off the one in Lightning.

I also run Blokada at the same time, to help.

@ildar
I just don't see any real pressing issues.

After trying many, many browsers, Lightning runs circles around them all.

Perhaps the way it is set up on your device is causing some issue?

I had to play around with it extensively for it to suit my needs, and have found that it is the only browser that actually can.

That being said, it would be nice to hear from Anthony.

**Comment by razorshiv** [comment]
Run circles around all? I would say that is a matter of opinion.

First, I have been loyal to Lightning for years mainly due to the fact that there were very few browsers "at the time" that catered to privacy. Today, the privacy space has grown so Lightning does need to step up or get left behind. A good example is bugs. For myself, I use the latest LineageOS and a Nexus 6P. Lightning has some glaring issues. No desktop bookmarks, no whitelisting and does not clear the separate webview data cache in its private app directory. Maybe because Lightning only supports stock releases? Oh well, guess the rom community is screwed. Add to that, no release since over a year ago. Yeah, people are saying but but but there are commits? Ok, what about those of us who do not have the know how to compile? If there is so much work being done behind the scenes then why are there no recent releases? How is this project active with no releases? I'm sure there is a reason but does anyone here know? Has Anthony spoken to his community about the future of his project? Not trying to be snarky, just asking questions. I'm actively watching this project, did I miss any official announcements of sorts?

There are other webview based browsers that work well. Take for instance one which I have not seen mentioned. Privacy Browser. This browserhas seen a lot of development in the last few years and worth a look. One feature that stands out is the ability to whilelist domains for things like cookies, javescript and DOM. Sort of like what noscript does for firefox. Pain in the ass to enable/disable javascript in lightning for certain websites and domains.......all the time......and for there same websites. Wish I could just leave javascript off but that is not realistic. In browser adblocking seems to be very well maintained. Although I also use AdAway in combination.

I'm just saying before anyone says that lightning is the best browser which I would have said for years, take a good look around. You just may be surprised at what you find. Lightning was and will always be my first love, but I have grown out of it. Privacy Browser is my new flame. If Lightning starts to look sexy again, I may just have to switch back to the old flame again, lol.

Regards

**Comment by Buntbart** [comment]
Can't find Stealth Browser or Lite Browser in F-Droid. Privacy Browser renders simple *.html files much too small by default, which can't be changed for the local files that I use. 

Actually, I didn't want to talk about other browsers either, but I wanted to know if I could still hope for any development at Lightning. Since anthonycr still hasn't expressed himself yet, this question is probably answered.

**Comment by Fuseteam** [comment]
i dunno this issue was opened just 9 days ago he might or might not still provide info
in the worse case scenario someone **with** the know how to compile and/or code can take it over untill anthony returns.

**Comment by puppykickr** [comment]
OK.
I tried Privacy Browser. It seems very secure, but images load up weird,
and it is taxing to go through all the settings.

It is nothing that I could install on someone else's phone for a simple set
up.

Oh yeah, and it is worthless as a default browser.

Crashes or wont load the page.
Same page loaded right up on Lightning.

I feel that if something isvnot broken, it should be left alone.

If the app was updated for every tiny little thing it would be like dealing
with Google Play.

YouTube and FaceBook have at least one and sometimesvtwo updates for no
good reason every week.

Stealth Browser and LiteSpeed Browser are on not on F-Droid, they are on
Google Play.

They are copies of Lightning, with the addition of Autofill.

Personally, the Autofill never worked right, and both apps grew to be
larger than Lightning in short order.

Neither one can handle the amount of open tabs or has the speed of
Lightning.

Grant Ryan Swan
(puppykicker)

**Comment by puppykickr** [comment]
@Buntbart

I use DuckDuckGo as the search engine, and under homepage in settings I select webpage and copy and paste this:


https://duckduckgo.com/?kae=t&kp=-2&kz=-1&kav=1&kn=1&kk=-1&kaj=u&kam=osm&kv=-1&kak=-1&kax=-1&kaq=-1&kap=-1&kao=-1&kau=-1&kg=p&k5=1&kac=-1&k1=-1



This gives all the settings for duckduckgo that i use, in a way that i can delete the cookies and still keep my settings intact.

**Comment by Buntbart** [comment]
@puppykickr I am using a handmade local *.html-file with my bookmarks as homepage. My main search-site is Startpage: https://www.startpage.com/do/mypage.pl?prfh=suggestionsEEE1N1Ngeo_mapEEE1N1Nwikipedia_iaEEE1N1Nother_iaEEE1N1Ndisable_open_in_new_windowEEE1N1Ndisable_video_family_filterEEE0N1Nenable_post_methodEEE1N1Nenable_proxy_safety_suggestEEE1N1NsslEEE1N1Nlanguage_uiEEEdeutschN1NlanguageEEEdeutschN1Nwt_unitEEEcelsiusN1Nnum_of_resultsEEE10N1Nlang_homepageEEEs/default/de/

**Comment by puppykickr** [comment]
The problems I had with StartPage are that the image menues are difficult
to navigate, and the way Google skews search results.

I find DuckDuckGo to be less biased, and the image menu much easier to
navigate.

Grant Ryan Swan
(puppykicker)

**Comment by Fuseteam** [comment]
actually it's only better on battery life if you have an oled screen, otherwise white is better for battery life (LCD), it definitely better on the eyes tho

**Comment by puppykickr** [comment]
@ Fuseteam

I beg to differ on that.
When I run a dark screen my phone runs nice and cool, with decent vattery life.
With a white screen it gets hot quick and the battery lasts about 25% or less than with the dark screen.

**Comment by kxxvii** [comment]
Hi there,

I happened see this conversation when I sifted through the issues. While I share your wishes about more frequent updates the author is under no obligation to cater to the demands of the users. This is a [free software](https://github.com/anthonycr/Lightning-Browser/blob/dev/LICENSE) project. [Section  6](https://github.com/anthonycr/Lightning-Browser/blob/dev/LICENSE#L263) and [section 7](https://github.com/anthonycr/Lightning-Browser/blob/dev/LICENSE#L282) of the license clearly states the conditions regarding warranty and limitation of liability.

I can see that people writing here seem to be doing so from a place of kindness (I will not single anyone out, that's _not_ my intention), and while I'm not a developer myself, the risk of burnout in free software is a real thing. Hence this admittedly somewhat moralistic comment.

Seeing as nobody addressed the license/burnout risk I just wanted to note this. As I said, I don't want to point fingers. Everything I've written above is of a general nature so I can't think of anything I might want to add other than this brief acknowledgement. I probably won't check out this issue again for that reason.

**Comment by Fuseteam** [comment]
@puppykickr then your phone doesn't have an lcd screen, lcd screen have a led array that is selectively blocks light to produce color. black would then involves blocking all the light.

**Comment by puppykickr** [comment]
It is LCD.
All I know is that a bright screen uses more power, as seen through a hot
phone and low battery life.

It is simple enough to test for yourself.

Get an app that measures battery charge in mAh in real time.  One that can
display over other apps.

Now put on a white screen.
Then put on a black screen.

The screen is black when it is off.

If the only bright parts are the text, then that is the part (the text) of
the screen using the most power.

If the screen is white, and text is black, it will use more power than the
other way.

Grant Ryan Swan
(puppykicker)

**Comment by bb010g** [comment]
Since @anthonycr is actively working on the project, I'd say it isn't dead. If he doesn't want to bother with releasing Play Store builds at this time, though, or even doing full releases, just cutting a new `4.6.0-alpha.1` or `5.0.0-alpha.1` release (marked as a pre-release on GitHub) should get F-Droid building it soon. If he doesn't want to bother with that either, F-Droid has [instructions on setting up published nightlies with Travis CI](https://f-droid.org/en/docs/Publishing_Nightly_Builds/) too.

**Comment by ildar** [comment]
I wonder if he gonna approach issues which are more then 300 already in
open state.

**Comment by puppykickr** [comment]
There is a new fork of Lightning on F-Droid.

It is called SimpleMobileWeb.

It is not in the default repositories, so you must enter settings on F-Droid and include the following repository:

https://apt.izzysoft.de/fdroid/repo?fingerprint=3BF0D6ABFEAE2F401707B6D966BE743BF0EEE49C2561B9BA39073711F628937A

There are other cool apps there as well.

I recently conversed with the developer of SimpleCookieWeb because the app has/had the same problem with crashing when making search selections (the biggest issue with Lightning).

This issue should be fixed with the next update.

**Comment by Buntbart** [comment]
Yesterday there was an update to Lightning 5.0.2 in F-Droid. So obviously Lightning *is* still alive! Thank you so much Anthony!
